// <auto-generated />
using System;
using CoreEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreEF.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20181219150144_UpdatedGradesTable")]
    partial class UpdatedGradesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreEF.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseName");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CoreEF.Models.Grade", b =>
                {
                    b.Property<string>("GradeName")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Id");

                    b.HasKey("GradeName");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("CoreEF.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("FirstName");

                    b.Property<int>("GradeId");

                    b.Property<string>("GradeName");

                    b.Property<decimal>("Height");

                    b.Property<string>("LastName");

                    b.Property<float>("Weight");

                    b.HasKey("StudentId");

                    b.HasIndex("GradeName");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CoreEF.Models.Student", b =>
                {
                    b.HasOne("CoreEF.Models.Grade", "Grade")
                        .WithMany("Students")
                        .HasForeignKey("GradeName");
                });
#pragma warning restore 612, 618
        }
    }
}
